"use client";
import Link from "next/link";
import { use, useEffect, useState } from "react";
import { ArrowLeft, CalendarDays, History, Save } from "lucide-react";
import { API_URL, apiFetch, moneyLocal, moneyUSD } from "@/lib/api";
import type { Employee, SalaryChange } from "@/lib/types";

export default function EmployeeDetail({params}:{params:Promise<{id:string}>}){const {id}=use(params);const [employee,setEmployee]=useState<Employee|null>(null),[history,setHistory]=useState<SalaryChange[]>([]),[salary,setSalary]=useState(""),[reason,setReason]=useState(""),[message,setMessage]=useState("");
 const load=()=>Promise.all([apiFetch<Employee>(`/employees/${id}/`),apiFetch<SalaryChange[]>(`/employees/${id}/salary_history/`)]).then(([e,h])=>{setEmployee(e);setSalary(e.annual_salary);setHistory(h)});useEffect(()=>{load()},[id]);
 async function save(){setMessage("");const r=await fetch(`${API_URL}/employees/${id}/`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({annual_salary:salary,salary_effective_date:new Date().toISOString().slice(0,10),salary_change_reason:reason})});if(!r.ok){setMessage(`Could not update: ${await r.text()}`);return}setReason("");setMessage("Salary updated and audit history recorded.");await load()}
 if(!employee)return <div className="loading">Loading employee…</div>;
 return <section><Link href="/employees" className="backLink"><ArrowLeft size={16}/>Back to employees</Link><div className="detailHero"><div className="avatar large">{employee.first_name[0]}{employee.last_name[0]}</div><div><div className="eyebrow">{employee.employee_id}</div><h1>{employee.full_name}</h1><p>{employee.job_title} · {employee.department} · {employee.country}</p></div></div>
 <div className="detailGrid"><div className="card panel"><div className="panelTitle"><div><span>Current compensation</span><small>Local salary with normalized USD reporting value</small></div></div><div className="salaryHero">{moneyLocal(employee.annual_salary,employee.currency)}<span>{moneyUSD(employee.annual_salary_usd)} reporting · FX {employee.exchange_rate_to_usd}</span></div><div className="formGrid"><label>Annual salary<input type="number" min="1" step="100" value={salary} onChange={e=>setSalary(e.target.value)}/></label><label>Reason<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="e.g. Market adjustment"/></label></div><button className="primaryBtn" onClick={save}><Save size={17}/>Save compensation</button>{message&&<div className="formMessage">{message}</div>}</div>
 <div className="card panel"><div className="panelTitle"><div><span>Employee details</span><small>Core employment metadata</small></div></div><div className="detailList"><div><span>Email</span><strong>{employee.email}</strong></div><div><span>Level</span><strong>{employee.job_level}</strong></div><div><span>Hire date</span><strong><CalendarDays size={15}/>{employee.hire_date}</strong></div><div><span>Currency</span><strong>{employee.currency}</strong></div></div></div></div>
 <div className="card panel"><div className="panelTitle"><div><span>Salary history</span><small>Append-only record created when compensation changes</small></div><History size={19}/></div>{history.length?<div className="timeline">{history.map(h=><div key={h.id} className="timelineRow"><div className="timelineDot"/><div><strong>{moneyLocal(h.previous_salary,h.previous_currency)} → {moneyLocal(h.new_salary,h.new_currency)}</strong><span>{h.effective_date} · {h.reason||"No reason provided"} · {moneyUSD(h.new_salary_usd)} reporting</span></div></div>)}</div>:<div className="mutedBox">No salary changes recorded yet.</div>}</div></section>}
