"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ChevronLeft, ChevronRight, Search, SlidersHorizontal } from "lucide-react";
import { apiFetch, moneyLocal, moneyUSD } from "@/lib/api";
import type { Employee, Metadata, Page } from "@/lib/types";
import { PageHeader } from "@/components/PageHeader";
import { EmptyState } from "@/components/EmptyState";

export default function Employees(){
 const [data,setData]=useState<Page<Employee>|null>(null),[meta,setMeta]=useState<Metadata|null>(null),[page,setPage]=useState(1),[search,setSearch]=useState(""),[department,setDepartment]=useState(""),[country,setCountry]=useState(""),[ordering,setOrdering]=useState("employee_id"),[loading,setLoading]=useState(true);
 const load=useCallback(()=>{setLoading(true);const q=new URLSearchParams({page:String(page),ordering});if(search)q.set("search",search);if(department)q.set("department",department);if(country)q.set("country",country);apiFetch<Page<Employee>>(`/employees/?${q}`).then(setData).finally(()=>setLoading(false))},[page,search,department,country,ordering]);
 useEffect(()=>{apiFetch<Metadata>("/employees/metadata/").then(setMeta)},[]);useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[load]);
 const pages=data?Math.ceil(data.count/25):1;
 return <section><PageHeader eyebrow="People" title="Employee compensation" description="Search and manage compensation records without loading the full organization into the browser."/>
 <div className="card filters"><label className="searchBox"><Search size={17}/><input value={search} onChange={e=>{setPage(1);setSearch(e.target.value)}} placeholder="Search name, ID, email or role…"/></label><div className="filterSelect"><SlidersHorizontal size={16}/><select value={department} onChange={e=>{setPage(1);setDepartment(e.target.value)}}><option value="">All departments</option>{meta?.departments.map(x=><option key={x}>{x}</option>)}</select></div><select className="select" value={country} onChange={e=>{setPage(1);setCountry(e.target.value)}}><option value="">All countries</option>{meta?.countries.map(x=><option key={x}>{x}</option>)}</select><select className="select" value={ordering} onChange={e=>setOrdering(e.target.value)}><option value="employee_id">Employee ID</option><option value="-annual_salary_usd">Salary: high to low</option><option value="annual_salary_usd">Salary: low to high</option><option value="first_name">Name</option></select></div>
 <div className="card tableCard">{loading?<div className="loading">Loading employees…</div>:data&&data.results.length?<><div className="tableWrap"><table><thead><tr><th>Employee</th><th>Department / role</th><th>Country</th><th>Local salary</th><th>Reporting salary</th><th></th></tr></thead><tbody>{data.results.map(e=><tr key={e.id}><td><div className="person"><div className="avatar">{e.first_name[0]}{e.last_name[0]}</div><div><strong>{e.full_name}</strong><span>{e.employee_id} · {e.email}</span></div></div></td><td><strong className="tablePrimary">{e.department}</strong><span className="tableSecondary">{e.job_title}</span></td><td>{e.country}</td><td><strong className="tablePrimary">{moneyLocal(e.annual_salary,e.currency)}</strong><span className="tableSecondary">{e.currency}</span></td><td>{moneyUSD(e.annual_salary_usd)}</td><td><Link className="textLink" href={`/employees/${e.id}`}>View →</Link></td></tr>)}</tbody></table></div><div className="pager"><span>{data.count.toLocaleString()} records · Page {page} of {pages}</span><div><button disabled={page<=1} onClick={()=>setPage(x=>x-1)}><ChevronLeft size={16}/>Previous</button><button disabled={page>=pages} onClick={()=>setPage(x=>x+1)}>Next<ChevronRight size={16}/></button></div></div></>:<EmptyState/>}</div></section>}
